// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqv0UDcEDBwXsn37bZe1HL76GEewi6SAQ',
    appId: '1:238836343332:android:c0a1899136ca1a277e2eb1',
    messagingSenderId: '238836343332',
    projectId: 'the-wall-37628',
    storageBucket: 'the-wall-37628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJm7ehIrY7JwUzAnZwGG-4jFbRuanysL8',
    appId: '1:238836343332:ios:764f75dff8bd32497e2eb1',
    messagingSenderId: '238836343332',
    projectId: 'the-wall-37628',
    storageBucket: 'the-wall-37628.firebasestorage.app',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtGS8DjV3cW5u0gWGpPIm1IlLwhfw3E5A',
    appId: '1:238836343332:web:47e9e867ba2697667e2eb1',
    messagingSenderId: '238836343332',
    projectId: 'the-wall-37628',
    authDomain: 'the-wall-37628.firebaseapp.com',
    storageBucket: 'the-wall-37628.firebasestorage.app',
  );
}
