// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0gpF452ez-I3AnbqURoWU5wW_ZpxAQIA',
    appId: '1:1679504668:android:ef56878cf8810c853736d9',
    messagingSenderId: '1679504668',
    projectId: 'chat-app-e2f23',
    storageBucket: 'chat-app-e2f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg1-_EjWjYQHZVjfFBu4kCgLrr4JaSXaM',
    appId: '1:1679504668:ios:dee9f2ce94d677de3736d9',
    messagingSenderId: '1679504668',
    projectId: 'chat-app-e2f23',
    storageBucket: 'chat-app-e2f23.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLkANgYLQ_Kin2-VdGO5sIVM8pZB9Wyj4',
    appId: '1:1679504668:web:b14a941ea13fb0ee3736d9',
    messagingSenderId: '1679504668',
    projectId: 'chat-app-e2f23',
    authDomain: 'chat-app-e2f23.firebaseapp.com',
    storageBucket: 'chat-app-e2f23.firebasestorage.app',
  );

}