// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KuOjECdltcliAKYT_L0AkW3Pg_bTncc',
    appId: '1:555741473704:android:c28292538f07ce671dcb9d',
    messagingSenderId: '555741473704',
    projectId: 'blood-donation-84f16',
    storageBucket: 'blood-donation-84f16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDySxej9ors7yhEvgE7a9MvHDTe0VdrUdc',
    appId: '1:555741473704:ios:1ed32753095219e01dcb9d',
    messagingSenderId: '555741473704',
    projectId: 'blood-donation-84f16',
    storageBucket: 'blood-donation-84f16.firebasestorage.app',
    iosBundleId: 'com.example.bloodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsIYIjj72G1qEiuXhdfaK1adHGKQdqUF0',
    appId: '1:555741473704:web:fc9943f14a64df2c1dcb9d',
    messagingSenderId: '555741473704',
    projectId: 'blood-donation-84f16',
    authDomain: 'blood-donation-84f16.firebaseapp.com',
    storageBucket: 'blood-donation-84f16.firebasestorage.app',
  );
}
