// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWiOvJzrwHstjbAoOmG7cLDspdngLQVYw',
    appId: '1:349039262453:android:9e81f0152705d1ada623bc',
    messagingSenderId: '349039262453',
    projectId: 'islamic-society-7730b',
    storageBucket: 'islamic-society-7730b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyHobmGLZQtOIElTwmwRC8nECc_F4xtnA',
    appId: '1:349039262453:ios:0820c5aa73adffb7a623bc',
    messagingSenderId: '349039262453',
    projectId: 'islamic-society-7730b',
    storageBucket: 'islamic-society-7730b.firebasestorage.app',
    iosBundleId: 'com.example.islamicSociety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpAA4TvGYaX2wUCOS4WmZMoBHM3WXdPnU',
    appId: '1:349039262453:web:79b761d453e15201a623bc',
    messagingSenderId: '349039262453',
    projectId: 'islamic-society-7730b',
    authDomain: 'islamic-society-7730b.firebaseapp.com',
    storageBucket: 'islamic-society-7730b.firebasestorage.app',
  );
}
